---
- name: 配置docker源
  shell: yum-config-manager --add-repo http://mirrors.aliyun.com/docker-ce/linux/centos/docker-ce.repo

- name: 安装docker18.06
  yum: name={{item}} state=present
  with_items:
     - device-mapper-persistent-data
     - lvm2
     - docker-ce-18.06.1.ce-3.el7


- name: 修改配置文件/usr/lib/systemd/system/docker.service
  lineinfile: dest=/usr/lib/systemd/system/docker.service  regexp='^ExecStart=' line='ExecStart=/usr/bin/dockerd  -H tcp://0.0.0.0:2375 -H unix:///var/run/docker.sock  --registry-mirror=https://ms3cfraz.mirror.aliyuncs.com\nEnvironment="HTTPS_PROXY=http://192.168.1.3:8123" "NO_PROXY=localhost,127.0.0.0/8,172.17.0.0/16"'

- name:  设置docker自启动
  service: name=docker state=started enabled=yes  daemon_reload=yes

- name: 添加阿里云K8S源
  copy: src=/etc/ansible/roles/docker_kubeadm/files/kubernetes.repo dest=/etc/yum.repos.d/kubernetes.repo

- name: 安装kubeadm{{k8s_version}}
  yum: name={{item}}-{{k8s_version}}-0.x86_64 state=present
  with_items:
        - kubeadm
        - kubectl
        - kubelet

- name: kubectl命令补全
  shell: yum install -y bash-completion  && kubectl completion bash > /etc/bash_completion.d/kubectl && echo "source <(kubectl completion bash)" >> /root/.bashrc

